# Generated by Django 2.0.4 on 2018-07-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Increse', '0002_auto_20180712_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='votes',
            new_name='posts',
        ),
    ]
